package dominio;
// Generated 25/12/2015 09:47:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Livro generated by hbm2java
 */
public class Livro  implements java.io.Serializable {


     private String isbn;
     private String autor;
     private String editora;
     private Serie serie;
     private String titulo;
     private String cidade;
     private Integer ano;
     private Integer edicao;
     private String sinopse;
     private String foto;
     private Set userLivros = new HashSet(0);

    public Livro() {
    }

	
    public Livro(String isbn) {
        this.isbn = isbn;
    }
    public Livro(String isbn, String autor, String editora, Serie serie, String titulo, String cidade, Integer ano, Integer edicao, String sinopse, String foto, Set userLivros) {
       this.isbn = isbn;
       this.autor = autor;
       this.editora = editora;
       this.serie = serie;
       this.titulo = titulo;
       this.cidade = cidade;
       this.ano = ano;
       this.edicao = edicao;
       this.sinopse = sinopse;
       this.foto = foto;
       this.userLivros = userLivros;
    }
   
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getEditora() {
        return this.editora;
    }
    
    public void setEditora(String editora) {
        this.editora = editora;
    }
    public Serie getSerie() {
        return this.serie;
    }
    
    public void setSerie(Serie serie) {
        this.serie = serie;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public Integer getEdicao() {
        return this.edicao;
    }
    
    public void setEdicao(Integer edicao) {
        this.edicao = edicao;
    }
    public String getSinopse() {
        return this.sinopse;
    }
    
    public void setSinopse(String sinopse) {
        this.sinopse = sinopse;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set getUserLivros() {
        return this.userLivros;
    }
    
    public void setUserLivros(Set userLivros) {
        this.userLivros = userLivros;
    }
}


