package dominio;
// Generated 25/12/2015 09:47:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Serie generated by hbm2java
 */
public class Serie  implements java.io.Serializable {


     private Integer id;
     private String titulo;
     private Set livros = new HashSet(0);

    public Serie() {
    }

    public Serie(String titulo, Set livros) {
       this.titulo = titulo;
       this.livros = livros;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set getLivros() {
        return this.livros;
    }
    
    public void setLivros(Set livros) {
        this.livros = livros;
    }




}


