package dominio;
// Generated 25/12/2015 09:47:43 by Hibernate Tools 4.3.1



/**
 * UserLivro generated by hbm2java
 */
public class UserLivro  implements java.io.Serializable {


     private Integer id;
     private Livro livro;
     private Usuario usuario;
     private Boolean gotit;
     private Boolean status;

    public UserLivro() {
    }

    public UserLivro(Livro livro, Usuario usuario, Boolean gotit, Boolean status) {
       this.livro = livro;
       this.usuario = usuario;
       this.gotit = gotit;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Livro getLivro() {
        return this.livro;
    }
    
    public void setLivro(Livro livro) {
        this.livro = livro;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Boolean getGotit() {
        return this.gotit;
    }
    
    public void setGotit(Boolean gotit) {
        this.gotit = gotit;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


