package dominio;
// Generated 25/12/2015 09:47:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String email;
     private String usuario;
     private String senha;
     private String foto;
     private Boolean status;
     private Set userLivros = new HashSet(0);

    public Usuario() {
    }
    
    public Usuario(String nome, String email, String usuario, String senha, String foto, Boolean status, Set userLivros) {
       this.nome = nome;
       this.email = email;
       this.usuario = usuario;
       this.senha = senha;
       this.foto = foto;
       this.status = status;
       this.userLivros = userLivros;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getUserLivros() {
        return this.userLivros;
    }
    
    public void setUserLivros(Set userLivros) {
        this.userLivros = userLivros;
    }

    @Override
    public String toString() {
        return "Usuario{" + "id=" + id + ", nome=" + nome + ", email=" + email + ", usuario=" + usuario + ", senha=" + senha + '}';
    }




}


